name: Build and push to GHCR

on:
  push:
    branches: [ main ]      # 触发条件：推送到 main
  workflow_dispatch:        # 也允许手动触发

permissions:                # 关键！让 GITHUB_TOKEN 拥有写包权限
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true                    # 构建完立即推送
        tags: |
          ghcr.io/${{ github.repository_owner }}/codemerge:latest
          ghcr.io/${{ github.repository_owner }}/codemerge:${{ github.sha }}